// Letterhead template definitions. Each renders the SAME structured data, but with different visual styles.
export const TEMPLATES = [
  {
    id: 'corporate-blue',
    name: 'Corporate Blue',
    category: 'Business',
    primary: '#1e3a8a',
    accent: '#3b82f6',
    headerStyle: 'gradient',
    font: 'Inter',
  },
  {
    id: 'ca-professional',
    name: 'CA Professional',
    category: 'CA / Tax',
    primary: '#0f172a',
    accent: '#b45309',
    headerStyle: 'doubleBorder',
    font: 'Georgia',
  },
  {
    id: 'legal-formal',
    name: 'Legal Formal',
    category: 'Lawyer',
    primary: '#451a03',
    accent: '#92400e',
    headerStyle: 'classic',
    font: 'Georgia',
  },
  {
    id: 'medical-care',
    name: 'Medical Care',
    category: 'Doctor / Hospital',
    primary: '#065f46',
    accent: '#10b981',
    headerStyle: 'sideBar',
    font: 'Inter',
  },
  {
    id: 'ngo-trust',
    name: 'NGO / Trust',
    category: 'NGO / Trust',
    primary: '#7c2d12',
    accent: '#f59e0b',
    headerStyle: 'classic',
    font: 'Georgia',
  },
  {
    id: 'modern-minimal',
    name: 'Modern Minimal',
    category: 'Real Estate / Service',
    primary: '#111827',
    accent: '#6366f1',
    headerStyle: 'minimal',
    font: 'Inter',
  },
]
